### ISSUE TITLE
"ERROR: cannot change working directory".

### ISSUE THREAD

**Issue by Rothdyt** [rstudio/blogdown#353]
Hi,

When I trying to use the [Academic](https://sourcethemes.com/academic/docs/install/) theme, I encounter the following issues when calling `blogdown:::serve_site()`,

```
"ERROR: cannot change working directory" 
```

on the viewer side  and

```
panic: BUG: Expected valid escape code after \, but got 'W'.

 [recovered]
	panic: BUG: Expected valid escape code after \, but got 'W'.
```

in the terminal.

I am not sure this is the bug from Hugo or blogdown. 

I also report the bug  [here](https://github.com/gcushen/hugo-academic/issues/850), where a screen shot is provided.

My blowdown version is 0.9.10. Hugo version is 0.53.

Detailed error information printed on the terminal.

```
> blogdown:::serve_site()
panic: BUG: Expected valid escape code after \, but got 'W'.

 [recovered]
	panic: BUG: Expected valid escape code after \, but got 'W'.



goroutine 1 [running]:
github.com/BurntSushi/toml.parse.func1(0xc000483138)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/!burnt!sushi/toml@v0.0.0-20170626110600-a368813c5e64/parse.go:46 +0x10c
panic(0x4b6a1e0, 0xc00026ff70)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
github.com/BurntSushi/toml.(*parser).bug(0xc00016a770, 0x4d0d3fc, 0x2f, 0xc000482c58, 0x1, 0x1)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/!burnt!sushi/toml@v0.0.0-20170626110600-a368813c5e64/parse.go:83 +0xfb
github.com/BurntSushi/toml.(*parser).replaceEscapes(0xc00016a770, 0xc000040181, 0x5a, 0x5b, 0x43)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/!burnt!sushi/toml@v0.0.0-20170626110600-a368813c5e64/parse.go:534 +0x2d8
github.com/BurntSushi/toml.(*parser).value(0xc00016a770, 0x6, 0xc00032395e, 0x63, 0x48, 0xc00032394c, 0xc, 0x101, 0xc000483018)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/!burnt!sushi/toml@v0.0.0-20170626110600-a368813c5e64/parse.go:167 +0x1c7e
github.com/BurntSushi/toml.(*parser).topLevel(0xc00016a770, 0x12, 0xc000323000, 0x0, 0x44)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/!burnt!sushi/toml@v0.0.0-20170626110600-a368813c5e64/parse.go:134 +0x7a3
github.com/BurntSushi/toml.parse(0xc000323000, 0x2c4e, 0xc00016a770, 0x4edb7a0, 0x568dc60)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/!burnt!sushi/toml@v0.0.0-20170626110600-a368813c5e64/parse.go:62 +0x23e
github.com/BurntSushi/toml.Decode(0xc000323000, 0x2c4e, 0x4b4f900, 0xc00000e1d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/!burnt!sushi/toml@v0.0.0-20170626110600-a368813c5e64/decode.go:115 +0x22a
github.com/BurntSushi/toml.Unmarshal(0xc000320000, 0x2c4e, 0x2e4e, 0x4b4f900, 0xc00000e1d0, 0x0, 0xc000483310)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/!burnt!sushi/toml@v0.0.0-20170626110600-a368813c5e64/decode.go:25 +0x8a
github.com/gohugoio/hugo/parser/metadecoders.Decoder.unmarshal(0x2c, 0xc000320000, 0x2c4e, 0x2e4e, 0x4ca1c2d, 0x4, 0x4b4f900, 0xc00000e1d0, 0x2c4e, 0x4ef2100)
	/private/tmp/hugo-20181224-11684-1jke1hj/hugo-0.53/src/github.com/gohugoio/hugo/parser/metadecoders/decoder.go:122 +0x6cb
github.com/gohugoio/hugo/parser/metadecoders.Decoder.UnmarshalToMap(0x2c, 0xc000320000, 0x2c4e, 0x2e4e, 0x4ca1c2d, 0x4, 0x2e4e, 0x0, 0x0)
	/private/tmp/hugo-20181224-11684-1jke1hj/hugo-0.53/src/github.com/gohugoio/hugo/parser/metadecoders/decoder.go:64 +0xc2
github.com/gohugoio/hugo/parser/metadecoders.Decoder.UnmarshalFileToMap(0x2c, 0x4ef1580, 0x568caa0, 0xc0000361e0, 0x2a, 0x0, 0x0, 0xc0004834f8)
	/private/tmp/hugo-20181224-11684-1jke1hj/hugo-0.53/src/github.com/gohugoio/hugo/parser/metadecoders/decoder.go:81 +0x11b
github.com/gohugoio/hugo/config.loadConfigFromFile(0x4ef1580, 0x568caa0, 0xc0000361e0, 0x2a, 0x1, 0x0, 0x0)
	/private/tmp/hugo-20181224-11684-1jke1hj/hugo-0.53/src/github.com/gohugoio/hugo/config/configLoader.go:72 +0x59
github.com/gohugoio/hugo/config.FromFileToMap(0x4ef1580, 0x568caa0, 0xc0000361e0, 0x2a, 0x1, 0x0, 0x0)
	/private/tmp/hugo-20181224-11684-1jke1hj/hugo-0.53/src/github.com/gohugoio/hugo/config/configLoader.go:56 +0x49
github.com/gohugoio/hugo/hugolib.configLoader.loadConfig(0x4ef1580, 0x568caa0, 0x0, 0x0, 0xc000036094, 0x1e, 0xc000036094, 0x1e, 0xc000036180, 0x25, ...)
	/private/tmp/hugo-20181224-11684-1jke1hj/hugo-0.53/src/github.com/gohugoio/hugo/hugolib/config.go:220 +0x243
github.com/gohugoio/hugo/hugolib.LoadConfig(0x4ef1580, 0x568caa0, 0x0, 0x0, 0xc000036094, 0x1e, 0xc000036094, 0x1e, 0xc000036180, 0x25, ...)
	/private/tmp/hugo-20181224-11684-1jke1hj/hugo-0.53/src/github.com/gohugoio/hugo/hugolib/config.go:131 +0x32f
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc00012a0c0, 0xc0003e0001, 0x4edb260, 0xc0000b8008)
	/private/tmp/hugo-20181224-11684-1jke1hj/hugo-0.53/src/github.com/gohugoio/hugo/commands/commandeer.go:278 +0x3be
github.com/gohugoio/hugo/commands.newCommandeer(0x1, 0xc00024d900, 0x4eda500, 0xc000348fd0, 0xc000349650, 0x0, 0x0, 0x0, 0x4bda7e0, 0xc0003aed01, ...)
	/private/tmp/hugo-20181224-11684-1jke1hj/hugo-0.53/src/github.com/gohugoio/hugo/commands/commandeer.go:160 +0x193
github.com/gohugoio/hugo/commands.initializeConfig(0x4bd0001, 0xc00024d900, 0x4eda500, 0xc000348fd0, 0xc000349650, 0xc000483c38, 0xc000483c08, 0x0)
	/private/tmp/hugo-20181224-11684-1jke1hj/hugo-0.53/src/github.com/gohugoio/hugo/commands/hugo.go:120 +0x76
github.com/gohugoio/hugo/commands.(*commandsBuilder).newHugoCmd.func1(0xc00035bb80, 0xc00039ce60, 0x0, 0xa, 0x0, 0x0)
	/private/tmp/hugo-20181224-11684-1jke1hj/hugo-0.53/src/github.com/gohugoio/hugo/commands/commands.go:155 +0x94
github.com/spf13/cobra.(*Command).execute(0xc00035bb80, 0xc0000bc010, 0xa, 0xa, 0xc00035bb80, 0xc0000bc010)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0xc00035bb80, 0xc000348fd0, 0xc0001448c0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/gohugoio/hugo/commands.Execute(0xc0000bc010, 0xa, 0xa, 0x8, 0xc000483f88, 0x4007520, 0xc000094058)
	/private/tmp/hugo-20181224-11684-1jke1hj/hugo-0.53/src/github.com/gohugoio/hugo/commands/hugo.go:86 +0xad
main.main()
	/private/tmp/hugo-20181224-11684-1jke1hj/hugo-0.53/src/github.com/gohugoio/hugo/main.go:27 +0x7a
createTcpServer: address already in use
```

**Comment by yihui** [comment]
I'm pretty sure this is not a **blogdown** issue, but either a Hugo issue or the hugo-academic theme issue. I'll reply to @gcushen in a second. Thanks!
